SystemReport: Don't call property `parentNode()` and `setAttribute()` on null
Icinga/icingaweb2-module-reporting pull request #136
Opened 2022-08-02 08:54 UTC by jhoxhaa

fix #129

2022-08-02 08:58 UTC, jhoxhaa commented
@cla-bot

2022-08-02 09:31 UTC, jhoxhaa commented
@cla-bot check

2022-08-02 09:48 UTC, bobapple commented
@cla-bot check

2022-09-05 07:38 UTC, lippserd requested changes

2022-09-05 07:38 UTC, lippserd commented on library/Reporting/Reports/SystemReport.php
> +
Please remove the newline.

2022-09-05 07:38 UTC, lippserd commented on library/Reporting/Reports/SystemReport.php
> +        if ($style) {
Please use `!== null`.

2022-09-05 07:38 UTC, lippserd commented on library/Reporting/Reports/SystemReport.php
> +        if ($title) {
Please use `!== null`.

2022-09-05 07:38 UTC, lippserd commented on library/Reporting/Reports/SystemReport.php
> +        if ($meta) {
Please use `!== null`.

2022-09-05 07:38 UTC, lippserd commented on library/Reporting/Reports/SystemReport.php
> +        if (($el = $doc->getElementsByTagName('div')->item(0)) !== null) {
All other blocks also do not set the variable in the `if`, so please do the same here, e.g.

```
$div = ...
if ($div !== null) {
    ...
}

2022-10-26 09:30 UTC, lippserd commented
@jhoxhaa Can you please check why this is even necessary? According to the issue, this only fails when the report is created from a schedule.

2022-11-04 09:39 UTC, nilmerg requested changes
While the error is gone, the resulting report isn't readable anymore now: 
[system (Current Day) 2022-11-04 1038.pdf](https://github.com/Icinga/icingaweb2-module-reporting/files/9936935/system.Current.Day.2022-11-04.1038.pdf)

2022-11-04 12:53 UTC, nilmerg approved these changes

2022-11-07 14:38 UTC, lippserd approved these changes

2022-11-07 14:38 UTC, merged