ScheduleForm: Add `Send Report Now` button
Icinga/icingaweb2-module-reporting pull request #137
Opened 2022-08-02 14:34 UTC by jhoxhaa

2022-11-29 09:37 UTC, yhabteab commented
> Can't see `send report now` button here :)

My bad! This is not the right form! 🙈

2023-01-12 13:09 UTC, yhabteab commented
## Blocked by

- https://github.com/Icinga/icingaweb2-module-reporting/pull/167

2023-03-15 09:59 UTC, yhabteab requested changes

2023-03-15 09:59 UTC, yhabteab commented on library/Reporting/Web/Forms/ScheduleForm.php
> +            'label'          => $action->getName(),
You should use `$this->translate(Send Report Now)` like the PR title and not the action name.

2023-03-15 09:59 UTC, yhabteab commented on library/Reporting/Web/Forms/ScheduleForm.php
>          $values = $this->getValues();
```suggestion
         $values = $this->getValues();
        if ($this->getPopulatedValue('send')) {
            $action = new $values['action']();
            $action->execute($this->report, $values);

            Notification::success('Report sent successfully');

            return;
        }
```

2023-03-15 11:55 UTC, yhabteab approved these changes

2023-03-15 15:13 UTC, yhabteab approved these changes

2023-03-15 15:16 UTC, yhabteab commented
@lippserd Do you want to have a look?

2023-03-15 15:32 UTC, lippserd commented on library/Reporting/Web/Forms/ScheduleForm.php
> +            Notification::success(t('Report sent successfully'));
Please replace `t()` with `$this->translate()`. After that it's free to merge.

2023-03-15 15:32 UTC, lippserd approved these changes

2023-03-15 15:57 UTC, merged