TimeframeForm: Use localDateTime instead of Flatpickr
Icinga/icingaweb2-module-reporting pull request #151
Opened 2022-10-12 14:57 UTC by jhoxhaa

fix #128

2022-10-26 09:32 UTC, lippserd commented
@jhoxhaa Please rebase and resolve merge conflicts.

Does the textual datetime description still work? For example `-1 hour`.

2022-11-04 10:34 UTC, nilmerg requested changes
With this, a textual input is only allowed for `start` and `end` simultaneously. A fixed datetime for `end` only doesn't make much sense, but for `start`. Consider a report that covers results *since 01-01-2022 00:00:00*. Of course, this is the same as the default timeframe `Current Year`, just expressed differently, but it shows that this example is not unreasonable. I'd opt for both expressions as a fixed date is more comprehensible as such a relative expression: `first day of January this year midnight`. (Especially easier to input, with the help of a widget) Though, wait for @lippserd's opinion before changing this.

What you can do right now:
* Update `ScheduleForm` so that it also uses a `localDateTime` element from now on
* Remove all traces from the `flatpickr` in this module
* Remove the `DecoratedElement` trait

2022-11-04 10:34 UTC, nilmerg commented on application/controllers/TimeframeController.php
> +            'start-end' => $checkboxValue,
I don't quite like that this is part of the controller action. This should be handled inside the form. There you can access the populated values with `getPopulatedValue()`.

2022-11-04 10:34 UTC, nilmerg commented on library/Reporting/Web/Forms/TimeframeForm.php
> +            'label'         => 'Start',
The placeholder is now translated, please do so for labels as well.

2022-11-07 09:22 UTC, jhoxhaa commented
> With this, a textual input is only allowed for `start` and `end` simultaneously. A fixed datetime for `end` only doesn't make much sense, but for `start`. Consider a report that covers results _since 01-01-2022 00:00:00_. Of course, this is the same as the default timeframe `Current Year`, just expressed differently, but it shows that this example is not unreasonable. I'd opt for both expressions as a fixed date is more comprehensible as such a relative expression: `first day of January this year midnight`. (Especially easier to input, with the help of a widget) Though, wait for @lippserd's opinion before changing this.

Do you mean we should use fixed datetime only or that we should be able to use both expressions at the same time? 🤔

2022-11-07 09:24 UTC, nilmerg commented
Currently it's only fixed + fixed or relative + relative, what I'd like to have is: fixed + relative

2023-01-12 13:22 UTC, yhabteab commented
Once this is ready, please make sure that this issue doesn't occur anymore!

- https://github.com/Icinga/icingaweb2-module-reporting/issues/172

2023-03-15 16:33 UTC, closed without merging