ReportForm: Add description to the form elements
Icinga/icingaweb2-module-reporting pull request #162
Opened 2022-11-23 14:07 UTC by jhoxhaa

2023-01-12 14:37 UTC, yhabteab requested changes
In addition to the requested changes, consider doing the following.

- If the method call and the description do not fit on the same line, then it is best to put the description on a separate line. Example:
    ```php
    [
         ... => $this->translate(
             'Description here'
         ),
    ]
   ```
    And when it still doesn't fit in the same line, you can simply wrap to the next line.
- Usually it is better to add the description attribute as the **last one**. If you have e.g. multiline description right at the beginning of the array, then it makes things messy.
   ```php
   [
      Other attributes here,
      'description' => ...
   ]
   ```

2023-01-12 14:37 UTC, yhabteab commented on library/Reporting/Web/Forms/ReportForm.php
> +                . 'It will be used when exported to pdf, json or csv format and also when you list the reports in cli'),
I would rephrase this as follows: 
`A unique name of this report. It is used when exporting to pdf, json or csv format and also when listing the reports in the cli`

2023-01-13 11:49 UTC, yhabteab requested changes

2023-01-13 11:49 UTC, yhabteab commented on library/Reporting/Web/Forms/ReportForm.php
> +                . 'and also when listing the reports in the cli'
Missing whitespace!

2023-01-13 11:49 UTC, yhabteab commented on library/Reporting/Web/Forms/ReportForm.php
> +            )
Please align the double arrow operators `=>` correctly.

2023-01-13 16:59 UTC, yhabteab approved these changes

2023-01-16 08:48 UTC, nilmerg requested changes
Please also mark the element and option labels for translation.

2023-01-16 08:49 UTC, nilmerg approved these changes
Nvm. That's what #175 does.

2023-01-16 16:10 UTC, merged