Form Refactoring
Icinga/icingaweb2-module-reporting pull request #167
Opened 2022-12-08 14:11 UTC by TAINCER

This removes the Multiple Submit Buttons Hack from `ScheduleForm`, `TemplateForm`, and `TimeFrameForm`. it also adds PHPDocs and Typo annotation where possible.

fixes #164

2022-12-09 09:57 UTC, yhabteab requested changes
That's still being used though!

https://github.com/Icinga/icingaweb2-module-reporting/blob/17600800bbb00f5160df50476d8fceb9b933ca51/library/Reporting/Web/Controller.php#L12-L19

2022-12-09 09:57 UTC, yhabteab commented on library/Reporting/Web/Forms/TemplateForm.php
> +     */
We use `inheritDoc` only when adding custom ones in addition to the parent docs.

2022-12-09 09:57 UTC, yhabteab commented on library/Reporting/Web/Forms/TemplateForm.php
> +     */
same here!

2022-12-09 09:57 UTC, yhabteab commented on library/Reporting/Web/Forms/TemplateForm.php
> +            $this->getDb()->delete('template', ['id = ?' => $this->template->id]);
Forget to return here?

2023-01-30 14:33 UTC, lippserd requested changes

2023-01-30 14:33 UTC, lippserd commented on library/Reporting/Web/Forms/ScheduleForm.php
> +    public static function fromReport(Report $report): ScheduleForm
Fix that for the other forms as well please.

2023-01-30 14:33 UTC, lippserd commented on library/Reporting/Web/Forms/ScheduleForm.php
> +     * Creates a new `ScheduleForm` instance with a given Report
Fix that for the other forms as well please.

2023-02-02 08:19 UTC, lippserd commented
@yhabteab Do you want to have a final look here?

2023-02-02 08:42 UTC, yhabteab approved these changes
LFTM as well! :)

2023-02-02 09:04 UTC, merged