Provide migration hook
Icinga/icingaweb2-module-reporting pull request #188
Opened 2023-07-10 08:35 UTC by yhabteab

## Blocked by
- https://github.com/Icinga/icingaweb2-module-reporting/pull/156

2023-09-12 14:01 UTC, nilmerg requested changes

2023-09-12 14:01 UTC, nilmerg commented on library/Reporting/ProvidedHook/DbMigration.php
> +    protected function getSchemaQueryFor(string $version): Query
this is obsolete, right?

2023-09-12 14:19 UTC, yhabteab commented on library/Reporting/ProvidedHook/DbMigration.php
> +    protected function getSchemaQueryFor(string $version): Query
Nope!

2023-09-12 15:25 UTC, nilmerg submitted a review, later dismissed

2023-09-15 12:51 UTC, nilmerg approved these changes

2023-09-15 14:37 UTC, nilmerg approved these changes

2023-09-19 15:07 UTC, nilmerg approved these changes

2023-09-19 15:08 UTC, merged