Enhance modal form redirects
Icinga/icingaweb2-module-reporting pull request #194
Opened 2023-07-27 11:51 UTC by yhabteab

2023-08-09 13:01 UTC, lippserd commented
@yhabteab This is not ready, right?

2023-08-09 13:05 UTC, yhabteab commented
> @yhabteab This is not ready, right?

It's ready, but its kind of waiting for https://github.com/Icinga/icingaweb2/pull/5068 to be merged.

2023-08-11 12:56 UTC, nilmerg requested changes
* the export dropdown isn't usable while the report is loading. (Fixed by https://github.com/Icinga/ipl-web/pull/188)
* Apply `outline: none` to `.content.container:focus`.

Sidenote:

the tabs should use `data-base-target=_main`. Otherwise the detail keeps open while switching.

2023-08-11 12:56 UTC, nilmerg commented on application/controllers/ReportController.php
> +        $this->addContent(new HtmlElement('p'));
Consider to use a element without a "meaning". I.e. `HtmlString::create('&nbsp;')` or `div`.

2023-08-11 12:56 UTC, nilmerg commented on application/controllers/ReportController.php
>              $this->addContent(Error::show($e));
An error is also shown with tabs I suppose? Should also be added to the document directly.

2023-08-11 12:56 UTC, nilmerg commented on application/controllers/ReportsController.php
> +                    $this
Don't break here pls, looks weird. You continue calling methods on the response. Not on the controller.

2023-08-11 14:15 UTC, nilmerg approved these changes
LGTM! The referenced Web PR is merged (kind of)

2023-08-13 20:39 UTC, lippserd commented
I don't know if it's related to the framework or the changes here, but as soon as I remove a report, the report list is refreshed twice. The clone action also triggers a refresh, which is not required.

2023-08-14 08:36 UTC, yhabteab commented
> I don't know if it's related to the framework or the changes here, but as soon as I remove a report, the report list is refreshed twice.

It's a framework bug.

> The clone action also triggers a refresh, which is not required.

By "triggers a refresh" do you mean that the `col2` container is updated after the redirection or that the `col1` container is refreshed as well?

2023-09-08 08:11 UTC, nilmerg requested changes

2023-09-08 08:11 UTC, nilmerg commented on phpstan-baseline.neon
> +			count: 3
We have a solution for this, so please fix this properly.

2023-09-08 08:53 UTC, nilmerg commented
Shouldn't the cloned report be visible in the detail, instead of the source report?

2023-09-08 08:55 UTC, yhabteab commented
> Shouldn't the cloned report be visible in the detail, instead of the source report?

No clue 🤷!

2023-09-08 09:10 UTC, nilmerg commented
I'd say so. At least does the refresh of col2 make no sense currently, as nothing changed. And if I clone a report and want to schedule/send it afterwards, I don't have to search for it in the list.

2023-09-12 08:29 UTC, nilmerg requested changes
Please fix the conflict

2023-09-12 08:29 UTC, nilmerg commented on application/controllers/ReportController.php
> +                $this->closeModalAndRefreshRemainingViews(
This works differently when on Icinga Web v2.12. Just use redirectNow.

2023-09-12 09:52 UTC, nilmerg approved these changes

2023-09-12 09:55 UTC, nilmerg requested changes
Oh no, wait. The time frame items still open a modal.

2023-09-12 10:02 UTC, nilmerg commented
Never mind. But please use `openInModal` where applicable. (As you noted by yourself)

2023-09-12 11:09 UTC, nilmerg approved these changes

2023-09-12 11:52 UTC, merged