Recommend package installs & enhance installation & configuration docs
Icinga/icingaweb2-module-reporting pull request #204
Opened 2023-09-12 12:44 UTC by yhabteab

fixes #196

2023-09-12 13:48 UTC, nilmerg approved these changes
Seems fine

2023-09-18 06:31 UTC, lippserd requested changes

2023-09-18 06:31 UTC, lippserd commented on doc/03-Configuration.md
> +## Icinga Reporting Daemon
This section needs a little adjustment. Packages will install the systemd service automatically. And I would add `--now` to the `systemctl enable` command to start the daemon right away as it's periodically reloading the configuration anyway.

2023-09-18 09:55 UTC, nilmerg requested changes

2023-09-18 09:55 UTC, nilmerg commented on doc/03-Configuration.md
> +Afterwards, you can run the following command to enable and start the daemon.
> Afterwards,

 After what?

2023-09-18 11:12 UTC, nilmerg submitted a review, later dismissed

2023-09-20 13:41 UTC, nilmerg approved these changes

2023-10-16 15:22 UTC, nilmerg requested changes

2023-10-16 15:22 UTC, nilmerg commented on doc/03-Configuration.md
> +Configuring the Icinga Reporting database backend now.
~~Configuring the Icinga Reporting~~
That should not be required to repeat here.

Instead, tell what's stored inside the database if you want a description for this section.

2023-10-16 15:22 UTC, nilmerg commented on doc/03-Configuration.md
> +1. Create a new resource for the Icinga Reporting via the `Configuration -> Application -> Resources` menu.
~~the~~ Icinga Reporting

2023-10-16 15:22 UTC, nilmerg commented on doc/03-Configuration.md
> +2. Configure the resource you just created as the database connection for the Icinga Reporting module using the
~~the~~ Icinga Reporting ~~module~~

2023-10-17 12:28 UTC, nilmerg approved these changes
I've also tested this locally as if rendered on the website. Looks fine, albeit the notice in 03-Configuration.md about the install without packages will not be hidden there, as the template macros are not evaluated in this context. But that's not a problem here.

2023-10-17 12:34 UTC, merged