Fix migrate schedule config procedure
Icinga/icingaweb2-module-reporting pull request #220
Opened 2023-11-14 11:54 UTC by yhabteab

fixes #216

2023-11-14 14:43 UTC, nilmerg submitted a review, later dismissed

2023-11-14 14:52 UTC, yhabteab commented
Tested also UI based migrations.

2023-11-14 15:41 UTC, nilmerg commented on doc/80-Upgrading.md
> +automation if you're an Icinga Director user. For those who are not using the latest version of Icinga Web, please follow the instructions below.
Please break this line as was previously the case

2023-11-15 12:33 UTC, nilmerg requested changes

2023-11-15 12:33 UTC, nilmerg commented on schema/mysql-upgrades/1.0.0.sql
> +  IF session_time_zone NOT LIKE '+%:%' AND CONVERT_TZ(FROM_UNIXTIME(1699903042), session_time_zone, '+00:00') IS NULL THEN
offsets may also be negative

2023-11-15 12:33 UTC, nilmerg commented on doc/80-Upgrading.md
> +> If you're not using Icinga Web migration automation, you may [populate](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html#time-zone-installation)
*you may need to*

2023-11-15 12:33 UTC, nilmerg commented on doc/80-Upgrading.md
> +> all the system named time zone information into your MSQL/MariaDB server. Otherwise, the migration will not succeed
*the migration may not*

2023-11-15 12:33 UTC, nilmerg commented on doc/80-Upgrading.md
> +> and will produce an SQL error.
you can remove this imho, that the migration might not succeed is sufficient.

2023-11-15 14:32 UTC, nilmerg commented on schema/mysql-upgrades/1.0.0.sql
> +  IF (session_time_zone NOT LIKE '+%:%' OR session_time_zone NOT LIKE '-%:%') AND CONVERT_TZ(FROM_UNIXTIME(1699903042), session_time_zone, '+00:00') IS NULL THEN
If it's *like* +%:%, it's *unlike* -%:%
If it's *like* -%:%, it's *unlike* +%:%

You want *if unlike +%:% and unlike -%:% and convert_tz(...) is null*, don't you?

2023-11-16 07:56 UTC, nilmerg approved these changes

2023-11-16 08:11 UTC, merged