Fix/timeframe form datetime handling
Icinga/icingaweb2-module-reporting pull request #244
Opened 2024-07-23 09:25 UTC by sukhwinder33445

fixes https://github.com/Icinga/icingaweb2-module-reporting/issues/240

2024-09-27 11:40 UTC, raviks789 commented on library/Reporting/Web/Forms/TimeframeForm.php
> +            }
IMO, this is not necessary, as the field for end time is required.

2025-03-03 14:08 UTC, nilmerg requested changes
Remove the autosubmit functionality. It messes up keyboard navigation.

2025-03-03 14:08 UTC, nilmerg commented on library/Reporting/Web/Forms/TimeframeForm.php
> +            }
+1

2025-03-06 15:24 UTC, nilmerg approved these changes

2025-03-06 15:24 UTC, merged