Db: Fix current week timeframe end
Icinga/icingaweb2-module-reporting pull request #246
Opened 2024-08-28 12:02 UTC by sukhwinder33445

2024-09-24 13:38 UTC, raviks789 commented on schema/mysql-upgrades/1.1.0.sql
> +UPDATE timeframe SET end = 'now' WHERE name = 'Current Week';
Insert the new version into `reporting_schema` table.

```sql
INSERT INTO reporting_schema (version, timestamp, success, reason)
  VALUES ('1.1.0', unix_timestamp() * 1000, 'y', NULL);
```

2024-09-24 13:38 UTC, raviks789 commented on schema/pgsql-upgrades/1.1.0.sql
> +UPDATE timeframe SET end = 'now' WHERE name = 'Current Week';
Same here.

2024-09-26 13:13 UTC, raviks789 approved these changes

2025-03-03 14:13 UTC, nilmerg commented
Is there an issue? A ticket? Or how did this come up?

2025-03-05 15:30 UTC, sukhwinder33445 commented
I noticed this issue by accident when I was testing other PRs.

2025-03-06 15:26 UTC, sukhwinder33445 commented
Assuming the week starts on monday and today is thursday, it would create reports until upcoming sunday, so future ones, which is actually wrong.

2025-03-06 15:44 UTC, nilmerg requested changes
Oh, now I see it as well. You're right.

Then please adjust the version number, 1.0.3 is the next one.

2025-03-07 09:13 UTC, nilmerg approved these changes

2025-03-07 09:13 UTC, merged